name: CI Build

on:
  push:
    branches: [ "C-M-Y" ]
  pull_request:
    branches: [ "C-M-Y" ]
  workflow_dispatch:

jobs:
  try_to_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26c
      - name: Change VersionName to Nightly Version
        run: |
          sed -i 's/\(versionName ".*\) ([0-9]\{4\}\.[0-9]\{2\}\.[0-9]\{2\})"/\1 (Nightly)('"$(date "+%Y-%m-%d %T")"')"/' hokiworker/android_app/app/build.gradlesed -i 's/\(versionName ".*\) ([0-9]\{4\}\.[0-9]\{2\}\.[0-9]\{2\})"/\1 (Nightly)('"$(date "+%Y-%m-%d %T")"')"/' hokiworker/android_app/app/build.gradle
          sed -i 's/\(versionName ".*\) ([0-9]\{4\}\.[0-9]\{2\}\.[0-9]\{2\})"/\1 (Nightly)('"$(date "+%Y-%m-%d %T")"')"/' hokiworker/android_app/app/build.gradlesed -i 's/\(versionName ".*\) ([0-9]\{4\}\.[0-9]\{2\}\.[0-9]\{2\})"/\1 (Nightly)('"$(date "+%Y-%m-%d %T")"')"/' hokiworker/android_app/library/build.gradle
      - name: Build CI Version
        run: cd ./hokiworker/cmd_exe/jni ; ndk-build ; cd ../../android_app ; chmod 0777 ./gradlew ; ./gradlew library:assembleRelease ; ./gradlew app:assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CI.ziP
          path: |
            hokiworker/cmd_exe/libs
            hokiworker/android_app/library/build/outputs/aar/release/library-release.aar
            hokiworker/android_app/app/build/outputs/apk/release/app-release.apk